spring:
  data:
    mongodb:
      host: mongodb+srv://rafaelteixeirarnnt:8299QQZnUjZvP3a3@fuiegoxxtei.w2tfekx.mongodb.net/?retryWrites=true&w=majority&appName=fuiegoxxtei
      port: 27017
      database: fuiegoxxtei
      username: rafaelteixeirarnnt
      password: 8299QQZnUjZvP3a3

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
