spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: fuiegoxxtei
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
