spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: fuiegoxxtei
      username: root
      password: root

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
